---
# cluster name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
# environment: |
#   HTTP_PROXY=http://proxy-name:8000
#   HTTPS_PROXY=http://proxy-name:8000
#   NO_PROXY=127.0.0.1,localhost,main-node,node01,node02,node03
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  # Worker IPs are incremented from the control IP.
  control_ip: 10.0.0.10
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
nodes:
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 2
    cpu: 2
    memory: 2048
# mount additional shared folders from the host into each virtual machine.
# note that the project directory is automatically mounted at /vagrant.
# shared_folders:
#   - host_path: ../images
#     vm_path: /vagrant/images
# to skip the dashboard installation, sets its version to an empty value or comment it out:
software:
  box: bento/ubuntu-24.04
  flannel: 0.24.4
  dashboard: 2.7.0
  kubernetes: 1.31.0-*

  os: xUbuntu_24.04
